version: '3'
services:
    dmit-vue-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dmit-vue-app
        ports:
            - 8888:80
    #nginx:
    #    image: nginx:alpine
    #    container_name: dmit-nginx-app
    #    volumes:
    #        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #    ports:
    #        - 80:80
    #    depends_on:
    #        - dmit-vue-app
