version: '3'
services:
    dmit-vue-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dmit-vue-app
        ports:
            - 8888:80
        networks:
            - dmit_network

    dmit-nginx-app:
        image: nginx:alpine
        container_name: dmit-nginx-app
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8889:80
        depends_on:
            - dmit-vue-app
        networks:
            - dmit_network

networks:
    dmit_network:
        external: true
