version: '3'
services:
    dmit-vue-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dmit-vue-app
        ports:
            - 8888:80
        networks:
            - dmit_network

networks:
    dmit_network:
        external: true
