# Use the node image from official Docker Hub
FROM node:20.15.0 as build-stage

RUN mkdir /app
# set the working directory
WORKDIR /app

# Copia los archivos de entorno
COPY .env.development .env.development

# Copy the working directory in the container
COPY package*.json ./

ENV NODE_OPTIONS="--max-old-space-size=4096"

# Update npm to the latest version
RUN npm install -g npm@10.9.2

# Install the project dependecies
# if you npm then npm install
RUN npm install

# Copy the rest of the project files to the container
COPY . .

#Build the Vue.js application to the production mode to dist folder
# here also if you use npm then npm run build
RUN npm run build:dev

# use the lighweight Nignx image from the previus state to the nginx container
FROM nginx:stable-alpine as production-stage

# Set working directory to nginx asset directory
WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf ./*

# Copy the build application from the previos state to the Nginx container
# her we can see the path of the build application and the path where we want to copy it
COPY --from=build-stage /app/dist .

# Copy the nginx configuration file
# here should be the same name as the nginx configuration file in the project
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose the port 80
EXPOSE 3131

# start nginx to server the application
ENTRYPOINT ["nginx", "-g", "daemon off;"]
