import type { RFC_2822 } from 'moment';
import type { Iva } from './Iva';

export const COMPANY_MODEL: string = 'App/Model/Company';

export const CUIT_ID: number = 25;

export const URL_UPLOAD_AVATAR: string = 'http://localhost:8001/api/uploadAvatar';

export enum AFIP_INSCRIPTION {
	IVA_RESPONSABLE_INSCRIPTO = 1,
	IVA_RESPONSABLE_NO_INSCRIPTO = 2,
	IVA_NO_RESPONSABLE = 3,
	IVA_SUJETO_EXENTO = 4,
	CONSUMIDOR_FINAL = 5,
	RESPONSABLE_MONOTRIBUTO = 6,
	SUJETO_NO_CATEGORIZADO = 7,
	PROVEEDOR_DEL_EXTERIOR = 8,
	CLIENTE_DEL_EXTERIOR = 9,
	IVA_LIBERADO = 10,
	IVA_RESPONSABLE_INSCRIPTO_AGENTE_DE_PERCEPCION = 11,
	PEQUEÑO_CONTRIBUYENTE = 12,
	MONOTRIBUTISTA_SOCIAL = 13,
	PEQUEÑO_CONTRIBUYENTE_SOCIAL = 14,
}

export enum INVOICE_TYPE {
	FACTURA = 1,
	NOTA_DE_DEBITO = 2,
	NOTA_DE_CREDITO = 3,
	FACTURA_A = 1,
	FACTURA_B = 6,
	FACTURA_C = 11,
	NOTA_DEBITO_A = 2,
	NOTA_DEBITO_B = 7,
	NOTA_DEBITO_C = 12,
	NOTA_CREDITO_A = 3,
	NOTA_CREDITO_B = 8,
	NOTA_CREDITO_C = 13,
}

export const INVOICE_CANT_REG = 1;

export const SELECT_INVOICE_TYPE = {
	[INVOICE_TYPE.FACTURA_A]: INVOICE_TYPE.FACTURA,
	[INVOICE_TYPE.FACTURA_B]: INVOICE_TYPE.FACTURA,
	[INVOICE_TYPE.FACTURA_C]: INVOICE_TYPE.FACTURA,
	[INVOICE_TYPE.NOTA_DEBITO_A]: INVOICE_TYPE.NOTA_DE_DEBITO,
	[INVOICE_TYPE.NOTA_DEBITO_B]: INVOICE_TYPE.NOTA_DE_DEBITO,
	[INVOICE_TYPE.NOTA_DEBITO_C]: INVOICE_TYPE.NOTA_DE_DEBITO,
	[INVOICE_TYPE.NOTA_CREDITO_A]: INVOICE_TYPE.NOTA_DE_CREDITO,
	[INVOICE_TYPE.NOTA_CREDITO_B]: INVOICE_TYPE.NOTA_DE_CREDITO,
	[INVOICE_TYPE.NOTA_CREDITO_C]: INVOICE_TYPE.NOTA_DE_CREDITO,
};

export enum AFIP_IVAS {
	AFIP_CODE_CERO = 3,
	AFIP_CODE_DIEZ_COMA_CINCO = 4,
	AFIP_CODE_VEINTI_UNO = 5,
	AFIP_CODE_VEINTI_SIETE = 6,
	AFIP_CODE_CINCO = 8,
	AFIP_CODE_DOS_COMA_CINCO = 9,
}

export const AFIP_IVA: Iva[] = [
	{ code: '3', name: '0%', percentage: 0 },
	{ code: '4', name: '10,50%', percentage: 10.5 },
	{ code: '5', name: '21%', percentage: 21 },
	{ code: '6', name: '27%', percentage: 27 },
	{ code: '8', name: '5%', percentage: 5 },
	{ code: '9', name: '2,50%', percentage: 2.5 },
];

// SE UTILIZA PARA DEFINIR EL HEIGHT Y WIDTH DEL DIV DONDE SE
// IMPRIMIRAN LOS COMENTARIOS DE LOS COMPROBANTES DE VENTAS
export const HTML2CANVAS_SCALE = {
	scale_02: {
		scale: 0.2,
		width: '910px',
		height: '500px',
	},
};
